name = "OceanTurb"
uuid = "d848d694-35fd-11e9-1c91-9995598ac29e"
authors = ["Gregory Wagner <wagner.greg@gmail.com>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
